/**
 * The SPI flash chip a JEDEC id names: its name, its capacity in kilobytes
 * where a source lists one, and the source its name came from.
 *
 * GENERATED by `Skills/update-jedec-ids/scripts/gen_jedec_web.py` from
 * upstream's own `JedecIDs.swift` — the generator of record, which keeps the
 * table current from three sources, in order of precedence when both know an
 * id:
 *   1. `common/descriptor.cpp` of github.com/LongSoft/UEFITool, branch
 *      `new_engine` — the `jedecIdToUString` table.
 *   2. `drivers/mtd/spi-nor/<vendor>.c` of the Linux kernel, master (GPL-2.0)
 *      — the SPI-NOR tables, entries with a three-byte id and a name.
 *   3. `flashchips/*.c` of github.com/flashrom/flashrom, branch `main` — the
 *      SPI chips probed by RDID.
 * A size is the first that any source lists, in the same order, also for an
 * entry named by UEFITool. Do not edit by hand: the next regeneration
 * overwrites it.
 *
 * Licence: the kernel's tables and flashrom are GPL-2.0. What is taken from
 * them is facts — a JEDEC id, a vendor and part name, a capacity — which
 * are not a copyrightable expression; no code, comment or structure of
 * theirs is copied, only those values, restated in this table's own form.
 * The names are the vendors' own part numbers.
 *
 * What this holds: the name of the SPI flash chip a JEDEC id stands for.
 * A flash descriptor's VSCC table lists the chips the board's firmware was
 * built to drive, by id alone, and an id is not something a bench can read.
 * The descriptor's detail panel shows the name beside it.
 */

/**
 * Where an entry's name was read from.
 *
 * @upstream Packages/UEFIImage/Sources/UEFIImage/JedecIDs.swift#JedecIDs.Source
 */
export type JedecSource = "uefiTool" | "linux" | "flashrom";

/**
 * What the catalogue knows of a chip: its name, its capacity where a source
 * lists one, and the source its name came from.
 *
 * @upstream Packages/UEFIImage/Sources/UEFIImage/JedecIDs.swift#JedecIDs.Chip
 */
export interface JedecChip {
  /** @upstream Packages/UEFIImage/Sources/UEFIImage/JedecIDs.swift#JedecIDs.Chip.name */
  readonly name: string;
  /**
   * Capacity in kilobytes, when a source lists it.
   *
   * @upstream Packages/UEFIImage/Sources/UEFIImage/JedecIDs.swift#JedecIDs.Chip.sizeKB
   */
  readonly sizeKB: number | undefined;
  /** @upstream Packages/UEFIImage/Sources/UEFIImage/JedecIDs.swift#JedecIDs.Chip.source */
  readonly source: JedecSource;
}

const TABLE: Readonly<Record<number, JedecChip>> = {
  // Winbond
  15675408: { name: "Winbond W25X05", sizeKB: 64, source: "uefiTool" },
  15675409: { name: "Winbond W25X10", sizeKB: 128, source: "uefiTool" },
  15675410: { name: "Winbond W25X20", sizeKB: 256, source: "uefiTool" },
  15675411: { name: "Winbond W25X40", sizeKB: 512, source: "uefiTool" },
  15675412: { name: "Winbond W25X80", sizeKB: 1024, source: "uefiTool" },
  15675413: { name: "Winbond W25X16", sizeKB: 2048, source: "uefiTool" },
  15675414: { name: "Winbond W25X32", sizeKB: 4096, source: "uefiTool" },
  15675415: { name: "Winbond W25X64", sizeKB: 8192, source: "uefiTool" },
  15679506: { name: "Winbond W25Q20", sizeKB: 256, source: "uefiTool" },
  15679507: { name: "Winbond W25Q40", sizeKB: 512, source: "uefiTool" },
  15679508: { name: "Winbond W25Q80", sizeKB: 1024, source: "uefiTool" },
  15679509: { name: "Winbond W25Q16", sizeKB: 2048, source: "uefiTool" },
  15679510: { name: "Winbond W25Q32", sizeKB: 4096, source: "uefiTool" },
  15679511: { name: "Winbond W25Q64", sizeKB: 8192, source: "uefiTool" },
  15679512: { name: "Winbond W25Q128", sizeKB: 16384, source: "uefiTool" },
  15679513: { name: "Winbond W25Q256", sizeKB: 32768, source: "uefiTool" },
  15679520: { name: "Winbond W25Q512", sizeKB: 65536, source: "uefiTool" },
  15687697: { name: "Winbond W25Q10", sizeKB: undefined, source: "uefiTool" },
  15687698: { name: "Winbond W25Q20", sizeKB: 256, source: "uefiTool" },
  15687699: { name: "Winbond W25Q40", sizeKB: 512, source: "uefiTool" },
  15687700: { name: "Winbond W25Q80", sizeKB: 1024, source: "uefiTool" },
  15687701: { name: "Winbond W25Q16", sizeKB: 2048, source: "uefiTool" },
  15687702: { name: "Winbond W25Q32", sizeKB: 4096, source: "uefiTool" },
  15687703: { name: "Winbond W25Q64", sizeKB: 8192, source: "uefiTool" },
  15687704: { name: "Winbond W25Q128", sizeKB: 16384, source: "uefiTool" },
  15687705: { name: "Winbond W25Q256", sizeKB: 32768, source: "uefiTool" },
  15692056: { name: "Winbond W25M256", sizeKB: undefined, source: "uefiTool" },
  15692057: { name: "Winbond W25M512", sizeKB: 65536, source: "uefiTool" },
  // Macronix
  12722195: { name: "Macronix MX25L40", sizeKB: 512, source: "uefiTool" },
  12722196: { name: "Macronix MX25L80", sizeKB: 1024, source: "uefiTool" },
  12722197: { name: "Macronix MX25L16", sizeKB: 2048, source: "uefiTool" },
  12722198: { name: "Macronix MX25U16", sizeKB: 4096, source: "uefiTool" },
  12722199: { name: "Macronix MX25L64", sizeKB: 8192, source: "uefiTool" },
  12722200: { name: "Macronix MX25L128", sizeKB: 16384, source: "uefiTool" },
  12722201: { name: "Macronix MX25L256", sizeKB: 32768, source: "uefiTool" },
  12722202: { name: "Macronix MX66L512", sizeKB: 65536, source: "uefiTool" },
  12723221: { name: "Macronix MX25L16", sizeKB: 2048, source: "uefiTool" },
  12723477: { name: "Macronix MX25L16", sizeKB: 2048, source: "uefiTool" },
  12723508: { name: "Macronix MX25U80", sizeKB: 1024, source: "uefiTool" },
  12723509: { name: "Macronix MX25U16", sizeKB: 2048, source: "uefiTool" },
  12723510: { name: "Macronix MX25U32", sizeKB: 4096, source: "uefiTool" },
  12723511: { name: "Macronix MX25U64", sizeKB: 8192, source: "uefiTool" },
  12723512: { name: "Macronix MX25U128", sizeKB: 16384, source: "uefiTool" },
  12723513: { name: "Macronix MX25U256", sizeKB: 32768, source: "uefiTool" },
  12723514: { name: "Macronix MX25U512", sizeKB: 65536, source: "uefiTool" },
  12723735: { name: "Macronix MX25L64", sizeKB: undefined, source: "uefiTool" },
  12723736: { name: "Macronix MX25L128", sizeKB: 16384, source: "uefiTool" },
  12738070: { name: "Macronix MX25L32", sizeKB: 4096, source: "uefiTool" },
  12743960: { name: "Macronix MX77L12850F", sizeKB: undefined, source: "uefiTool" },
  12743961: { name: "Macronix MX77L25650F", sizeKB: 32768, source: "uefiTool" },
  12743962: { name: "Macronix MX77L51250F", sizeKB: undefined, source: "uefiTool" },
  12752151: { name: "Macronix MX25L64", sizeKB: 8192, source: "uefiTool" },
  // Micron
  2105364: { name: "Micron M25P80", sizeKB: 1024, source: "uefiTool" },
  2105365: { name: "Micron M25P16", sizeKB: 2048, source: "uefiTool" },
  2105366: { name: "Micron M25P32", sizeKB: 4096, source: "uefiTool" },
  2105367: { name: "Micron M25P64", sizeKB: 8192, source: "uefiTool" },
  2105368: { name: "Micron M25P128", sizeKB: 16384, source: "uefiTool" },
  2113553: { name: "Micron M45PE10", sizeKB: 128, source: "uefiTool" },
  2113554: { name: "Micron M45PE20", sizeKB: 256, source: "uefiTool" },
  2113555: { name: "Micron M45PE40", sizeKB: 512, source: "uefiTool" },
  2113556: { name: "Micron M45PE80", sizeKB: 1024, source: "uefiTool" },
  2113557: { name: "Micron M45PE16", sizeKB: 2048, source: "uefiTool" },
  2113559: { name: "Micron XM25QH64C", sizeKB: 8192, source: "uefiTool" },
  2113560: { name: "Micron XM25QH128C", sizeKB: 16384, source: "uefiTool" },
  2113561: { name: "Micron XM25QH256C", sizeKB: 32768, source: "uefiTool" },
  2114328: { name: "Micron XM25RH128C", sizeKB: 16384, source: "uefiTool" },
  2114329: { name: "Micron XM25RH256C", sizeKB: undefined, source: "uefiTool" },
  2114336: { name: "Micron XM25RH512C", sizeKB: undefined, source: "uefiTool" },
  2126100: { name: "Micron M25PX80", sizeKB: 1024, source: "uefiTool" },
  2126101: { name: "Micron M25PX16", sizeKB: 2048, source: "uefiTool" },
  2126102: { name: "Micron M25PX32", sizeKB: 4096, source: "uefiTool" },
  2126103: { name: "Micron M25PX64", sizeKB: 8192, source: "uefiTool" },
  2129937: { name: "Micron M25PE10", sizeKB: 128, source: "uefiTool" },
  2129938: { name: "Micron M25PE20", sizeKB: 256, source: "uefiTool" },
  2129939: { name: "Micron M25PE40", sizeKB: 512, source: "uefiTool" },
  2129940: { name: "Micron M25PE80", sizeKB: 1024, source: "uefiTool" },
  2129941: { name: "Micron M25PE16", sizeKB: 2048, source: "uefiTool" },
  2144789: { name: "Micron N25Q016", sizeKB: undefined, source: "uefiTool" },
  2144790: { name: "Micron N25Q032", sizeKB: 4096, source: "uefiTool" },
  2144791: { name: "Micron N25Q064", sizeKB: 8192, source: "uefiTool" },
  2144792: { name: "Micron N25Q128", sizeKB: 16384, source: "uefiTool" },
  2144793: { name: "Micron N25Q256", sizeKB: 32768, source: "uefiTool" },
  2144800: { name: "Micron N25Q512", sizeKB: 65536, source: "uefiTool" },
  2144801: { name: "Micron N25Q00A", sizeKB: 131072, source: "uefiTool" },
  2145045: { name: "Micron N25Q016", sizeKB: 2048, source: "uefiTool" },
  2145046: { name: "Micron N25Q032", sizeKB: 4096, source: "uefiTool" },
  2145047: { name: "Micron N25Q064", sizeKB: 8192, source: "uefiTool" },
  2145048: { name: "Micron MT25Q128", sizeKB: 16384, source: "uefiTool" },
  2145049: { name: "Micron MT25Q256", sizeKB: 32768, source: "uefiTool" },
  2145056: { name: "Micron MT25Q512", sizeKB: 65536, source: "uefiTool" },
  // Intel
  9013521: { name: "Intel 25F160S33B8", sizeKB: 2048, source: "uefiTool" },
  9013522: { name: "Intel 25F320S33B8", sizeKB: 4096, source: "uefiTool" },
  9013523: { name: "Intel 25F640S33B8", sizeKB: 8192, source: "uefiTool" },
  9013525: { name: "Intel 25F160S33T8", sizeKB: 2048, source: "uefiTool" },
  9013526: { name: "Intel 25F320S33T8", sizeKB: 4096, source: "uefiTool" },
  9013527: { name: "Intel 25F640S33T8", sizeKB: 8192, source: "uefiTool" },
  // Atmel / Adesto
  2044439: { name: "Atmel AT25SF641", sizeKB: undefined, source: "uefiTool" },
  2048534: { name: "Atmel AT25SL321", sizeKB: 4096, source: "uefiTool" },
  2048536: { name: "Atmel AT25SL128A", sizeKB: 16384, source: "uefiTool" },
  2048791: { name: "Atmel AT25SL641", sizeKB: undefined, source: "uefiTool" },
  2049280: { name: "Atmel AT26DF081", sizeKB: undefined, source: "uefiTool" },
  2049281: { name: "Atmel AT26DF081A", sizeKB: 1024, source: "uefiTool" },
  2049282: { name: "Atmel AT25DF081", sizeKB: 1024, source: "uefiTool" },
  2049536: { name: "Atmel AT26DF161", sizeKB: 2048, source: "uefiTool" },
  2049537: { name: "Atmel AT26DF161A", sizeKB: 2048, source: "uefiTool" },
  2049538: { name: "Atmel AT25DF161", sizeKB: 2048, source: "uefiTool" },
  2049792: { name: "Atmel AT25DF321", sizeKB: 4096, source: "uefiTool" },
  2049793: { name: "Atmel AT25DF321A", sizeKB: 4096, source: "uefiTool" },
  2050048: { name: "Atmel AT25DF641", sizeKB: 8192, source: "uefiTool" },
  2060312: { name: "Atmel AT25QF128", sizeKB: undefined, source: "uefiTool" },
  2065920: { name: "Atmel AT25DQ161", sizeKB: 2048, source: "uefiTool" },
  2066432: { name: "Atmel AT25DQ641", sizeKB: undefined, source: "uefiTool" },
  // Microchip
  12526913: { name: "Microchip SST25VF016B", sizeKB: 2048, source: "uefiTool" },
  12526922: { name: "Microchip SST25VF032B", sizeKB: 4096, source: "uefiTool" },
  12526989: { name: "Microchip SST25VF040B", sizeKB: 512, source: "uefiTool" },
  12526990: { name: "Microchip SST25VF080B", sizeKB: 1024, source: "uefiTool" },
  12526923: { name: "Microchip SST25VF064C", sizeKB: 8192, source: "uefiTool" },
  // EON / ESMT
  1847315: { name: "EON EN25Q40", sizeKB: 512, source: "uefiTool" },
  1847316: { name: "EON EN25Q80", sizeKB: 1024, source: "uefiTool" },
  1847317: { name: "EON EN25Q16", sizeKB: undefined, source: "uefiTool" },
  1847318: { name: "EON EN25Q32", sizeKB: 4096, source: "uefiTool" },
  1847319: { name: "EON EN25Q64", sizeKB: 8192, source: "uefiTool" },
  1847320: { name: "EON EN25Q128", sizeKB: 16384, source: "uefiTool" },
  1847572: { name: "EON EN25F80", sizeKB: 1024, source: "uefiTool" },
  1847573: { name: "EON EN25F16", sizeKB: 2048, source: "uefiTool" },
  1847574: { name: "EON EN25F32", sizeKB: 4096, source: "uefiTool" },
  1847575: { name: "EON EN25F64", sizeKB: 8192, source: "uefiTool" },
  1849361: { name: "EON EN25S10", sizeKB: 128, source: "uefiTool" },
  1849362: { name: "EON EN25S20", sizeKB: 256, source: "uefiTool" },
  1849363: { name: "EON EN25S40", sizeKB: 512, source: "uefiTool" },
  1849364: { name: "EON EN25S80", sizeKB: 1024, source: "uefiTool" },
  1849365: { name: "EON EN25S16", sizeKB: 2048, source: "uefiTool" },
  1849366: { name: "EON EN25S32", sizeKB: 4096, source: "uefiTool" },
  1849367: { name: "EON EN25S64", sizeKB: 8192, source: "uefiTool" },
  1863700: { name: "EON EN25QH80", sizeKB: undefined, source: "uefiTool" },
  1863701: { name: "EON EN25QH16", sizeKB: 2048, source: "uefiTool" },
  1863702: { name: "EON EN25QH32", sizeKB: 4096, source: "uefiTool" },
  1863703: { name: "EON EN25QH64", sizeKB: 8192, source: "uefiTool" },
  1863704: { name: "EON EN25QH128", sizeKB: 16384, source: "uefiTool" },
  1863705: { name: "EON EN25QH256", sizeKB: undefined, source: "uefiTool" },
  // GigaDevice
  13123604: { name: "GigaDevice GD25x80", sizeKB: 1024, source: "uefiTool" },
  13123605: { name: "GigaDevice GD25x16", sizeKB: 2048, source: "uefiTool" },
  13123606: { name: "GigaDevice GD25x32", sizeKB: 4096, source: "uefiTool" },
  13123607: { name: "GigaDevice GD25x64", sizeKB: 8192, source: "uefiTool" },
  13123608: { name: "GigaDevice GD25x128", sizeKB: 16384, source: "uefiTool" },
  13123609: { name: "GigaDevice GD25x256", sizeKB: 32768, source: "uefiTool" },
  13123610: { name: "GigaDevice GD25x512", sizeKB: 65536, source: "uefiTool" },
  13125402: { name: "GigaDevice GD25B512ME", sizeKB: undefined, source: "uefiTool" },
  13131797: { name: "GigaDevice GD25LQ16V", sizeKB: 2048, source: "uefiTool" },
  13131799: { name: "GigaDevice GD25Lx64", sizeKB: 8192, source: "uefiTool" },
  13131800: { name: "GigaDevice GD25Lx128", sizeKB: 16384, source: "uefiTool" },
  13131801: { name: "GigaDevice GD25LQ256C", sizeKB: 32768, source: "uefiTool" },
  // Fidelix
  16265749: { name: "Fidelix FM25Q16", sizeKB: undefined, source: "uefiTool" },
  16265750: { name: "Fidelix FM25Q32", sizeKB: undefined, source: "uefiTool" },
  16265751: { name: "Fidelix FM25Q64", sizeKB: undefined, source: "uefiTool" },
  16265752: { name: "Fidelix FM25Q128", sizeKB: undefined, source: "uefiTool" },
  // Spansion
  81941: { name: "Spansion S25FL116K", sizeKB: 2048, source: "uefiTool" },
  81942: { name: "Spansion S25FL132K", sizeKB: 4096, source: "uefiTool" },
  81943: { name: "Spansion S25FL164K", sizeKB: 8192, source: "uefiTool" },
  // AMIC Technology
  3616789: { name: "AMIC A25L016", sizeKB: 2048, source: "uefiTool" },
  3616790: { name: "AMIC A25L032", sizeKB: 4096, source: "uefiTool" },
  3620885: { name: "AMIC A25LQ16", sizeKB: 2048, source: "uefiTool" },
  3620886: { name: "AMIC A25LQ32A", sizeKB: 4096, source: "uefiTool" },
  3620887: { name: "AMIC A25LQ64", sizeKB: 8192, source: "uefiTool" },
  // PMC
  10352403: { name: "PMC Pm25LV080B", sizeKB: undefined, source: "uefiTool" },
  10352404: { name: "PMC Pm25LV016B", sizeKB: undefined, source: "uefiTool" },
  10352452: { name: "PMC Pm25LQ080C", sizeKB: undefined, source: "uefiTool" },
  10352453: { name: "PMC Pm25LQ016C", sizeKB: undefined, source: "uefiTool" },
  10352454: { name: "PMC Pm25LQ032C", sizeKB: undefined, source: "uefiTool" },
  10352507: { name: "PMC Pm25LV512A", sizeKB: undefined, source: "uefiTool" },
  10352508: { name: "PMC Pm25LV010A", sizeKB: undefined, source: "uefiTool" },
  10352509: { name: "PMC Pm25LV020", sizeKB: undefined, source: "uefiTool" },
  10352510: { name: "PMC Pm25LV040", sizeKB: undefined, source: "uefiTool" },
  // ISSI
  10313748: { name: "ISSI Ix25LP080", sizeKB: 1024, source: "uefiTool" },
  10313749: { name: "ISSI Ix25LP016", sizeKB: 2048, source: "uefiTool" },
  10313750: { name: "ISSI Ix25LP032", sizeKB: 4096, source: "uefiTool" },
  10313751: { name: "ISSI Ix25LP064", sizeKB: 8192, source: "uefiTool" },
  10313752: { name: "ISSI Ix25LP128", sizeKB: 16384, source: "uefiTool" },
  10313753: { name: "ISSI Ix25LP256", sizeKB: 32768, source: "uefiTool" },
  10317844: { name: "ISSI Ix25WP080", sizeKB: 1024, source: "uefiTool" },
  10317845: { name: "ISSI Ix25WP016", sizeKB: 2048, source: "uefiTool" },
  10317846: { name: "ISSI Ix25WP032", sizeKB: 4096, source: "uefiTool" },
  10317847: { name: "ISSI Ix25WP064", sizeKB: 8192, source: "uefiTool" },
  10317848: { name: "ISSI Ix25WP128", sizeKB: 16384, source: "uefiTool" },
  10317849: { name: "ISSI Ix25WP256", sizeKB: 32768, source: "uefiTool" },
  // linux
  66066: { name: "Spansion S25SL004A", sizeKB: 512, source: "linux" },
  66067: { name: "Spansion S25SL008A", sizeKB: 1024, source: "linux" },
  66068: { name: "Spansion S25SL016A", sizeKB: 2048, source: "linux" },
  66069: { name: "Spansion S25SL032A", sizeKB: 4096, source: "linux" },
  66070: { name: "Spansion S25SL064A", sizeKB: 8192, source: "linux" },
  81939: { name: "Spansion S25FL204K", sizeKB: 512, source: "linux" },
  81940: { name: "Spansion S25FL208K", sizeKB: 1024, source: "linux" },
  90135: { name: "Spansion S25FL064L", sizeKB: 8192, source: "linux" },
  90136: { name: "Spansion S25FL128L", sizeKB: 16384, source: "linux" },
  90137: { name: "Spansion S25FL256L", sizeKB: 32768, source: "linux" },
  1843222: { name: "EON EN25P32", sizeKB: 4096, source: "linux" },
  1843223: { name: "EON EN25P64", sizeKB: 8192, source: "linux" },
  2032640: { name: "Atmel AT26F004", sizeKB: 512, source: "linux" },
  2041088: { name: "Atmel AT45DB081D", sizeKB: 1024, source: "linux" },
  2049025: { name: "Atmel AT25DF041A", sizeKB: 512, source: "linux" },
  2049800: { name: "Atmel AT25FF321A", sizeKB: undefined, source: "linux" },
  2057729: { name: "Atmel AT25FS010", sizeKB: 128, source: "linux" },
  2057732: { name: "Atmel AT25FS040", sizeKB: 512, source: "linux" },
  2105360: { name: "Micron M25P05", sizeKB: 64, source: "linux" },
  2105361: { name: "Micron M25P10", sizeKB: 128, source: "linux" },
  2105362: { name: "Micron M25P20", sizeKB: 256, source: "linux" },
  2105363: { name: "Micron M25P40", sizeKB: 512, source: "linux" },
  2122518: { name: "Micron M25PX32-S1", sizeKB: 4096, source: "linux" },
  2125847: { name: "XMC XM25QH64A", sizeKB: 8192, source: "linux" },
  2125848: { name: "XMC XM25QH128A", sizeKB: 16384, source: "linux" },
  2126614: { name: "Micron M25PX32-S0", sizeKB: 4096, source: "linux" },
  2144802: { name: "Micron MT25QL02G", sizeKB: 262144, source: "linux" },
  2145057: { name: "Micron N25Q00A", sizeKB: 131072, source: "linux" },
  2145058: { name: "Micron MT25QU02G", sizeKB: 262144, source: "linux" },
  2906908: { name: "Micron MT35XU02G", sizeKB: 262144, source: "linux" },
  3430938: { name: "Spansion S28HL512T", sizeKB: undefined, source: "linux" },
  3430939: { name: "Spansion S28HL01GT", sizeKB: undefined, source: "linux" },
  3431194: { name: "Spansion S28HS512T", sizeKB: undefined, source: "linux" },
  3431195: { name: "Spansion S28HS01GT", sizeKB: undefined, source: "linux" },
  3431196: { name: "Spansion S28HS02GT", sizeKB: undefined, source: "linux" },
  6428178: { name: "SST SST25WF020A", sizeKB: 256, source: "linux" },
  6428179: { name: "SST SST25WF040B", sizeKB: 512, source: "linux" },
  8363296: { name: "ISSI IS25CD512", sizeKB: 64, source: "linux" },
  8363334: { name: "ISSI PM25LQ032", sizeKB: 4096, source: "linux" },
  9183254: { name: "ESMT F25L32PA", sizeKB: 4096, source: "linux" },
  9191702: { name: "ESMT F25L32QA-2S", sizeKB: 4096, source: "linux" },
  9191703: { name: "ESMT F25L64QA", sizeKB: 8192, source: "linux" },
  10305555: { name: "ISSI IS25LQ040B", sizeKB: 512, source: "linux" },
  12526849: { name: "SST SST25WF512", sizeKB: 64, source: "linux" },
  12526850: { name: "SST SST25WF010", sizeKB: 128, source: "linux" },
  12526851: { name: "SST SST25WF020", sizeKB: 256, source: "linux" },
  12526852: { name: "SST SST25WF040", sizeKB: 512, source: "linux" },
  12526853: { name: "SST SST25WF080", sizeKB: 1024, source: "linux" },
  12527169: { name: "SST SST26VF016B", sizeKB: 2048, source: "linux" },
  12527170: { name: "SST SST26VF032B", sizeKB: 4096, source: "linux" },
  12527171: { name: "SST SST26VF064B", sizeKB: 8192, source: "linux" },
  12527185: { name: "SST SST26WF016B", sizeKB: 2048, source: "linux" },
  12722192: { name: "Macronix MX25L512E", sizeKB: 64, source: "linux" },
  12722194: { name: "Macronix MX25L2005A", sizeKB: 256, source: "linux" },
  12722964: { name: "Macronix MX25V8035F", sizeKB: 1024, source: "linux" },
  12723506: { name: "Macronix MX25U2033E", sizeKB: 256, source: "linux" },
  12723507: { name: "Macronix MX25U4035", sizeKB: 512, source: "linux" },
  12723737: { name: "Macronix MX25L25655E", sizeKB: 32768, source: "linux" },
  12723739: { name: "Macronix MX66L1G55G", sizeKB: 131072, source: "linux" },
  12724245: { name: "Macronix MX25R1635F", sizeKB: 2048, source: "linux" },
  12724246: { name: "Macronix MX25R3235F", sizeKB: 4096, source: "linux" },
  13131798: { name: "GigaDevice GD25LQ32", sizeKB: 4096, source: "linux" },
  15683602: { name: "Winbond W25Q20BW", sizeKB: 256, source: "linux" },
  15683604: { name: "Winbond W25Q80", sizeKB: 1024, source: "linux" },
  15687712: { name: "Winbond W25Q512NWQ", sizeKB: 65536, source: "linux" },
  15691797: { name: "Winbond W25Q16JV-IM/JM", sizeKB: 2048, source: "linux" },
  15691798: { name: "Winbond W25Q32JV", sizeKB: 4096, source: "linux" },
  15691799: { name: "Winbond W25Q64JVM", sizeKB: 8192, source: "linux" },
  15691800: { name: "Winbond W25Q128JV", sizeKB: 16384, source: "linux" },
  15691801: { name: "Winbond W25Q256JVM", sizeKB: 32768, source: "linux" },
  15695894: { name: "Winbond W25Q32JWM", sizeKB: 4096, source: "linux" },
  15695895: { name: "Winbond W25Q64JWM", sizeKB: 8192, source: "linux" },
  15695896: { name: "Winbond W25Q128JWM", sizeKB: 16384, source: "linux" },
  15695897: { name: "Winbond W25Q256JWM", sizeKB: 32768, source: "linux" },
  15695904: { name: "Winbond W25Q512NWM", sizeKB: 65536, source: "linux" },
  // flashrom
  66073: { name: "Spansion S25FL256S......0", sizeKB: 32768, source: "flashrom" },
  73752: { name: "Spansion S25FL127S-256kB", sizeKB: 16384, source: "flashrom" },
  737298: { name: "XTX Technology Limited XT25F02E", sizeKB: 256, source: "flashrom" },
  737303: { name: "XTX Technology Limited XT25F64B", sizeKB: 8192, source: "flashrom" },
  737304: { name: "XTX Technology Limited XT25F128B", sizeKB: 16384, source: "flashrom" },
  1843216: { name: "Eon EN25B05", sizeKB: 64, source: "flashrom" },
  1843217: { name: "Eon EN25B10", sizeKB: 128, source: "flashrom" },
  1843218: { name: "Eon EN25B20", sizeKB: 256, source: "flashrom" },
  1843219: { name: "Eon EN25B40", sizeKB: 512, source: "flashrom" },
  1843220: { name: "Eon EN25B80", sizeKB: 1024, source: "flashrom" },
  1843221: { name: "Eon EN25B16", sizeKB: 2048, source: "flashrom" },
  1847568: { name: "Eon EN25F05", sizeKB: 64, source: "flashrom" },
  1847569: { name: "Eon EN25F10", sizeKB: 128, source: "flashrom" },
  1847570: { name: "Eon EN25F20", sizeKB: 256, source: "flashrom" },
  1847571: { name: "Eon EN25F40", sizeKB: 512, source: "flashrom" },
  1863960: { name: "Eon EN25QX128A", sizeKB: 16384, source: "flashrom" },
  2036737: { name: "Atmel AT25EU0041A", sizeKB: 512, source: "flashrom" },
  2037249: { name: "Atmel AT25EU0161A", sizeKB: 2048, source: "flashrom" },
  2041600: { name: "Atmel AT45DB321C", sizeKB: 4224, source: "flashrom" },
  2042144: { name: "Atmel AT45CS1282", sizeKB: 16896, source: "flashrom" },
  2048512: { name: "Atmel AT25DF011", sizeKB: 128, source: "flashrom" },
  2048768: { name: "Atmel AT25DF021", sizeKB: 256, source: "flashrom" },
  2048769: { name: "Atmel AT25DF021A", sizeKB: 256, source: "flashrom" },
  2049024: { name: "Atmel AT26DF041", sizeKB: 512, source: "flashrom" },
  2049032: { name: "Atmel AT25FF041A", sizeKB: 512, source: "flashrom" },
  2049539: { name: "Atmel AT25DL161", sizeKB: 2048, source: "flashrom" },
  2057472: { name: "Atmel AT25F512B", sizeKB: 64, source: "flashrom" },
  2065409: { name: "Atmel AT25SF041", sizeKB: 512, source: "flashrom" },
  2065665: { name: "Atmel AT25SF081", sizeKB: 1024, source: "flashrom" },
  2065921: { name: "Atmel AT25SF161", sizeKB: 2048, source: "flashrom" },
  2066177: { name: "Atmel AT25SF321", sizeKB: 4096, source: "flashrom" },
  2066689: { name: "Atmel AT25SF128A", sizeKB: 16384, source: "flashrom" },
  2113558: { name: "XMC XM25QH32C/XM25QH32D", sizeKB: 4096, source: "flashrom" },
  2113568: { name: "XMC XM25QH512C/XM25QH512D", sizeKB: 65536, source: "flashrom" },
  2113815: { name: "XMC XM25QU64C/XM25LU64C", sizeKB: 8192, source: "flashrom" },
  2113816: { name: "XMC XM25QU128C/XM25QU128D", sizeKB: 16384, source: "flashrom" },
  2113817: { name: "XMC XM25QU256C/XM25QU256D", sizeKB: 32768, source: "flashrom" },
  2113824: { name: "XMC XM25QU512C/XM25QU512D", sizeKB: 65536, source: "flashrom" },
  2114585: { name: "XMC XM25RU256C", sizeKB: 32768, source: "flashrom" },
  2117652: { name: "XMC XM25QU80B", sizeKB: 1024, source: "flashrom" },
  2117653: { name: "XMC XM25QU16C", sizeKB: 2048, source: "flashrom" },
  2117654: { name: "XMC XM25QU32C", sizeKB: 4096, source: "flashrom" },
  3616784: { name: "AMIC A25L512", sizeKB: 64, source: "flashrom" },
  3616785: { name: "AMIC A25L010", sizeKB: 128, source: "flashrom" },
  3616786: { name: "AMIC A25L020", sizeKB: 256, source: "flashrom" },
  3616787: { name: "AMIC A25L040", sizeKB: 512, source: "flashrom" },
  3616788: { name: "AMIC A25L080", sizeKB: 1024, source: "flashrom" },
  4857875: { name: "ESI ES25P40", sizeKB: 512, source: "flashrom" },
  4857876: { name: "ESI ES25P80", sizeKB: 1024, source: "flashrom" },
  4857877: { name: "ESI ES25P16", sizeKB: 2048, source: "flashrom" },
  6424082: { name: "Sanyo LE25FU206A", sizeKB: 256, source: "flashrom" },
  6424083: { name: "Sanyo LE25FU406C/LE25U40CMC", sizeKB: 512, source: "flashrom" },
  6426880: { name: "Sanyo LE25FW403A", sizeKB: 512, source: "flashrom" },
  6428160: { name: "Sanyo LE25FW203A", sizeKB: 256, source: "flashrom" },
  6428180: { name: "SST25WF080B", sizeKB: 1024, source: "flashrom" },
  6832146: { name: "Boya/BoHong Microelectronics BY25D20", sizeKB: 256, source: "flashrom" },
  6832147: { name: "Boya/BoHong Microelectronics BY25D40", sizeKB: 512, source: "flashrom" },
  6832148: { name: "Boya/BoHong Microelectronics B.25D80A", sizeKB: 1024, source: "flashrom" },
  6832149: { name: "Boya/BoHong Microelectronics B.25D16A", sizeKB: 2048, source: "flashrom" },
  6832151: { name: "Boya/BoHong Microelectronics B.25Q64AS", sizeKB: 8192, source: "flashrom" },
  6832152: { name: "Boya/BoHong Microelectronics B.25Q128AS", sizeKB: 16384, source: "flashrom" },
  8724499: { name: "PUYA P25Q40HB", sizeKB: 512, source: "flashrom" },
  8724501: { name: "PUYA P25Q16HB", sizeKB: 2048, source: "flashrom" },
  8732688: { name: "PUYA P25Q06H", sizeKB: 64, source: "flashrom" },
  8732689: { name: "PUYA P25Q11H", sizeKB: 128, source: "flashrom" },
  8732690: { name: "PUYA P25Q21H", sizeKB: 256, source: "flashrom" },
  8740883: { name: "PUYA P25D40SH", sizeKB: 512, source: "flashrom" },
  8740884: { name: "PUYA P25D80H", sizeKB: 1024, source: "flashrom" },
  8740886: { name: "PUYA P25D32SH/P25Q32SH", sizeKB: 4096, source: "flashrom" },
  9183252: { name: "ESMT F25L008A", sizeKB: 1024, source: "flashrom" },
  10293843: { name: "ISSI IS25WQ040", sizeKB: 512, source: "flashrom" },
  10294341: { name: "ISSI IS25LQ016", sizeKB: 2048, source: "flashrom" },
  10305558: { name: "ISSI IS25LQ032", sizeKB: 4096, source: "flashrom" },
  10313760: { name: "ISSI IS25LP512MG", sizeKB: 65536, source: "flashrom" },
  10313761: { name: "ISSI IS25LP01GJ", sizeKB: 131072, source: "flashrom" },
  10317842: { name: "ISSI IS25WP020", sizeKB: 256, source: "flashrom" },
  10317843: { name: "ISSI IS25WP040", sizeKB: 512, source: "flashrom" },
  10317856: { name: "ISSI IS25WP512MG", sizeKB: 65536, source: "flashrom" },
  10317857: { name: "ISSI IS25WP01GJ", sizeKB: 131072, source: "flashrom" },
  10561560: { name: "Fudan FM25W128", sizeKB: 16384, source: "flashrom" },
  10563856: { name: "Fudan FM25F005", sizeKB: 64, source: "flashrom" },
  10563857: { name: "Fudan FM25F01", sizeKB: 128, source: "flashrom" },
  10563858: { name: "Fudan FM25F02(A)", sizeKB: 256, source: "flashrom" },
  10563859: { name: "Fudan FM25F04(A)", sizeKB: 512, source: "flashrom" },
  10567699: { name: "Fudan FM25Q04", sizeKB: 512, source: "flashrom" },
  10567700: { name: "Fudan FM25Q08", sizeKB: 1024, source: "flashrom" },
  10567701: { name: "Fudan FM25Q16", sizeKB: 2048, source: "flashrom" },
  10567702: { name: "Fudan FM25Q32", sizeKB: 4096, source: "flashrom" },
  10567703: { name: "Fudan FM25Q64", sizeKB: 8192, source: "flashrom" },
  10567704: { name: "Fudan FM25Q128", sizeKB: 16384, source: "flashrom" },
  12197906: { name: "Zetta Device ZD25D20", sizeKB: 256, source: "flashrom" },
  12197907: { name: "Zetta Device ZD25D40", sizeKB: 512, source: "flashrom" },
  12526988: { name: "SST25VF020B", sizeKB: 256, source: "flashrom" },
  12722193: { name: "Macronix MX25L1005(C)/MX25L1006E", sizeKB: 128, source: "flashrom" },
  12722203: { name: "Macronix MX66L1G45G", sizeKB: 131072, source: "flashrom" },
  12722204: { name: "Macronix MX66L2G45G", sizeKB: 262144, source: "flashrom" },
  12722704: { name: "Macronix MX25L5121E", sizeKB: 64, source: "flashrom" },
  12722963: { name: "Macronix MX25V4035F", sizeKB: 512, source: "flashrom" },
  12722965: { name: "Macronix MX25V1635F", sizeKB: 2048, source: "flashrom" },
  12723515: { name: "Macronix MX66U1G45G", sizeKB: 131072, source: "flashrom" },
  12723516: { name: "Macronix MX66U2G45G", sizeKB: 262144, source: "flashrom" },
  12724240: { name: "Macronix MX25R512F", sizeKB: 64, source: "flashrom" },
  12724241: { name: "Macronix MX25R1035F", sizeKB: 128, source: "flashrom" },
  12724242: { name: "Macronix MX25R2035F", sizeKB: 256, source: "flashrom" },
  12724243: { name: "Macronix MX25R4035F", sizeKB: 512, source: "flashrom" },
  12724244: { name: "Macronix MX25R8035F", sizeKB: 1024, source: "flashrom" },
  12724247: { name: "Macronix MX25R6435F", sizeKB: 8192, source: "flashrom" },
  12743993: { name: "Macronix MX77U25650F", sizeKB: 32768, source: "flashrom" },
  12743994: { name: "Macronix MX77U51250F", sizeKB: 65536, source: "flashrom" },
  12748090: { name: "Macronix MX25LM51245G", sizeKB: 65536, source: "flashrom" },
  12754454: { name: "Macronix MX25L3255E", sizeKB: 4096, source: "flashrom" },
  13119764: { name: "GigaDevice GD25T80", sizeKB: 1024, source: "flashrom" },
  13123600: { name: "GigaDevice GD25Q512", sizeKB: 64, source: "flashrom" },
  13123601: { name: "GigaDevice GD25Q10", sizeKB: 128, source: "flashrom" },
  13123602: { name: "GigaDevice GD25Q20(B)", sizeKB: 256, source: "flashrom" },
  13123603: { name: "GigaDevice GD25Q40(B)", sizeKB: 512, source: "flashrom" },
  13124114: { name: "GigaDevice GD25VQ21B", sizeKB: 256, source: "flashrom" },
  13124115: { name: "GigaDevice GD25VQ40C", sizeKB: 512, source: "flashrom" },
  13124116: { name: "GigaDevice GD25VQ80C", sizeKB: 1024, source: "flashrom" },
  13124117: { name: "GigaDevice GD25VQ16C", sizeKB: 2048, source: "flashrom" },
  13124375: { name: "GigaDevice GD25F64F", sizeKB: 8192, source: "flashrom" },
  13124376: { name: "GigaDevice GD25F128F", sizeKB: 16384, source: "flashrom" },
  13124377: { name: "GigaDevice GD25F256F", sizeKB: 32768, source: "flashrom" },
  13131795: { name: "GigaDevice GD25LQ40", sizeKB: 512, source: "flashrom" },
  13131796: { name: "GigaDevice GD25LQ80", sizeKB: 1024, source: "flashrom" },
  13131802: { name: "GigaDevice GD25LB512MF/GD25LR512MF", sizeKB: 65536, source: "flashrom" },
  13132568: { name: "GigaDevice GD25LF128E", sizeKB: 16384, source: "flashrom" },
  13132569: { name: "GigaDevice GD25LF256F", sizeKB: 32768, source: "flashrom" },
  13132570: { name: "GigaDevice GD25LF512MF", sizeKB: 65536, source: "flashrom" },
  13133076: { name: "GigaDevice GD25WQ80E", sizeKB: 1024, source: "flashrom" },
  13133593: { name: "GigaDevice GD25LB256E/GD25LR256E", sizeKB: 32768, source: "flashrom" },
  13133594: { name: "GigaDevice GD25LB512ME/GD25LR512ME", sizeKB: 65536, source: "flashrom" },
  13971473: { name: "Nantronics N25S10", sizeKB: 128, source: "flashrom" },
  13971474: { name: "Nantronics N25S20", sizeKB: 256, source: "flashrom" },
  13971475: { name: "Nantronics N25S40", sizeKB: 512, source: "flashrom" },
  13971476: { name: "Nantronics N25S80", sizeKB: 1024, source: "flashrom" },
  13971477: { name: "Nantronics N25S16", sizeKB: 2048, source: "flashrom" },
  15671316: { name: "Winbond W25P80", sizeKB: 1024, source: "flashrom" },
  15671317: { name: "Winbond W25P16", sizeKB: 2048, source: "flashrom" },
  15671318: { name: "Winbond W25P32", sizeKB: 4096, source: "flashrom" },
  15679521: { name: "Winbond W25Q01JV", sizeKB: 131072, source: "flashrom" },
  15682071: { name: "Winbond W77Q64JV", sizeKB: 8192, source: "flashrom" },
  15682072: { name: "Winbond W77Q128JV", sizeKB: 16384, source: "flashrom" },
  15683603: { name: "Winbond W25Q40BW", sizeKB: 512, source: "flashrom" },
  15686428: { name: "Winbond W35T02NW", sizeKB: 262144, source: "flashrom" },
  15691808: { name: "Winbond W25Q512JV_M", sizeKB: 65536, source: "flashrom" },
  15698454: { name: "Winbond W77Q16JW", sizeKB: 2048, source: "flashrom" },
  15698455: { name: "Winbond W77Q64JW", sizeKB: 8192, source: "flashrom" },
  15698456: { name: "Winbond W77Q128JW", sizeKB: 16384, source: "flashrom" },
  15698459: { name: "Winbond W77Q01NWQ", sizeKB: 131072, source: "flashrom" },
  15699479: { name: "Winbond W77T64NW", sizeKB: 8192, source: "flashrom" },
  15699480: { name: "Winbond W77T12NW", sizeKB: 16384, source: "flashrom" },
  15699481: { name: "Winbond W77T25NWS", sizeKB: 32768, source: "flashrom" },
  15699482: { name: "Winbond W77T51NWD", sizeKB: 65536, source: "flashrom" },
  15699483: { name: "Winbond W77T01NWQ", sizeKB: 131072, source: "flashrom" },
  2140995603: { name: "PMC Pm25LV080B", sizeKB: 1024, source: "flashrom" },
  2140995604: { name: "PMC Pm25LV016B", sizeKB: 2048, source: "flashrom" },
  2140995616: { name: "PMC Pm25LD512(C)", sizeKB: 64, source: "flashrom" },
  2140995617: { name: "PMC Pm25LD010(C)", sizeKB: 128, source: "flashrom" },
  2140995618: { name: "PMC Pm25LD020(C)", sizeKB: 256, source: "flashrom" },
  2140995631: { name: "PMC Pm25LD256C", sizeKB: 32, source: "flashrom" },
  2140995650: { name: "PMC Pm25LQ020", sizeKB: 256, source: "flashrom" },
  2140995651: { name: "PMC Pm25LQ040", sizeKB: 512, source: "flashrom" },
  2140995652: { name: "PMC Pm25LQ080", sizeKB: 1024, source: "flashrom" },
  2140995653: { name: "PMC Pm25LQ016", sizeKB: 2048, source: "flashrom" },
  2140995654: { name: "PMC Pm25LQ032C", sizeKB: 4096, source: "flashrom" },
  2140995708: { name: "PMC Pm25LV010A", sizeKB: 128, source: "flashrom" },
  2140995709: { name: "PMC Pm25LV020", sizeKB: 256, source: "flashrom" },
  2140995710: { name: "PMC Pm25LD040(C)", sizeKB: 512, source: "flashrom" },
};

/**
 * The chip a 24-bit JEDEC id names — vendor byte, then the two device bytes —
 * or nothing for one this table does not know.
 *
 * @upstream Packages/UEFIImage/Sources/UEFIImage/JedecIDs.swift#JedecIDs.chip
 */
export function jedecChip(id: number): JedecChip | undefined {
  return TABLE[id];
}

/**
 * The name alone, where the caller does not want the rest of the entry.
 *
 * @upstream Packages/UEFIImage/Sources/UEFIImage/JedecIDs.swift#JedecIDs.name
 */
export function jedecName(id: number): string | undefined {
  return TABLE[id]?.name;
}

/**
 * How many chips the table knows, for the test that the generated file is the
 * whole of its sources rather than a truncated read of it.
 *
 * @upstream Packages/UEFIImage/Sources/UEFIImage/JedecIDs.swift#JedecIDs.count
 */
export const JEDEC_COUNT = Object.keys(TABLE).length;

/**
 * How many of them each source named.
 *
 * @upstream Packages/UEFIImage/Sources/UEFIImage/JedecIDs.swift#JedecIDs.count
 */
export function jedecCount(source: JedecSource): number {
  return Object.values(TABLE).filter((chip) => chip.source === source).length;
}
