#!/usr/bin/env python3
"""Convert upstream's generated JedecIDs.swift into the web's jedecIds.ts.

The upstream file (Packages/UEFIImage/Sources/UEFIImage/JedecIDs.swift) is the
generator of record for the chip catalogue: the update-jedec-ids skill there
scrapes UEFITool, the Linux kernel's SPI-NOR tables and flashrom, in that
precedence, and keeps each entry's source. This script translates that table
into TypeScript. It never reads the three sources itself, so the web cannot
drift from upstream's read of them — when the sources move, upstream's own
regeneration moves first, and this one follows.

Usage: gen_jedec_web.py [PATH-TO-JedecIDs.swift]

Without a path, the clone at $BYTERIPPER_REPO is read, or the sibling clone
at ../ByteRipper when that is empty. The script refuses to write under a
hundred entries: under a hundred, the read is truncated or the upstream
layout changed, and the right answer is not a smaller table.
"""

import os
import re
import sys
from pathlib import Path

SCRIPT = Path(__file__).resolve()
ROOT = SCRIPT.parents[3]
OUT = ROOT / "src" / "firmware" / "uefi" / "jedecIds.ts"

ENTRY = re.compile(
    r'^\s*(0x[0-9A-Fa-f]+): c\("([^"]+)", (nil|\d+), \.(uefiTool|linux|flashrom)\),\s*$'
)
GROUP = re.compile(r"^\s*// (.+)$")
TABLE_OPEN = "private static let table"
FLOOR = 100

HEADER = """/**
 * The SPI flash chip a JEDEC id names: its name, its capacity in kilobytes
 * where a source lists one, and the source its name came from.
 *
 * GENERATED by `Skills/update-jedec-ids/scripts/gen_jedec_web.py` from
 * upstream's own `JedecIDs.swift` — the generator of record, which keeps the
 * table current from three sources, in order of precedence when both know an
 * id:
 *   1. `common/descriptor.cpp` of github.com/LongSoft/UEFITool, branch
 *      `new_engine` — the `jedecIdToUString` table.
 *   2. `drivers/mtd/spi-nor/<vendor>.c` of the Linux kernel, master (GPL-2.0)
 *      — the SPI-NOR tables, entries with a three-byte id and a name.
 *   3. `flashchips/*.c` of github.com/flashrom/flashrom, branch `main` — the
 *      SPI chips probed by RDID.
 * A size is the first that any source lists, in the same order, also for an
 * entry named by UEFITool. Do not edit by hand: the next regeneration
 * overwrites it.
 *
 * Licence: the kernel's tables and flashrom are GPL-2.0. What is taken from
 * them is facts — a JEDEC id, a vendor and part name, a capacity — which
 * are not a copyrightable expression; no code, comment or structure of
 * theirs is copied, only those values, restated in this table's own form.
 * The names are the vendors' own part numbers.
 *
 * What this holds: the name of the SPI flash chip a JEDEC id stands for.
 * A flash descriptor's VSCC table lists the chips the board's firmware was
 * built to drive, by id alone, and an id is not something a bench can read.
 * The descriptor's detail panel shows the name beside it.
 */

"""

TYPES = """/**
 * Where an entry's name was read from.
 *
 * @upstream Packages/UEFIImage/Sources/UEFIImage/JedecIDs.swift#JedecIDs.Source
 */
export type JedecSource = "uefiTool" | "linux" | "flashrom";

/**
 * What the catalogue knows of a chip: its name, its capacity where a source
 * lists one, and the source its name came from.
 *
 * @upstream Packages/UEFIImage/Sources/UEFIImage/JedecIDs.swift#JedecIDs.Chip
 */
export interface JedecChip {
  /** @upstream Packages/UEFIImage/Sources/UEFIImage/JedecIDs.swift#JedecIDs.Chip.name */
  readonly name: string;
  /**
   * Capacity in kilobytes, when a source lists it.
   *
   * @upstream Packages/UEFIImage/Sources/UEFIImage/JedecIDs.swift#JedecIDs.Chip.sizeKB
   */
  readonly sizeKB: number | undefined;
  /** @upstream Packages/UEFIImage/Sources/UEFIImage/JedecIDs.swift#JedecIDs.Chip.source */
  readonly source: JedecSource;
}

"""

FOOTER = """
/**
 * The chip a 24-bit JEDEC id names — vendor byte, then the two device bytes —
 * or nothing for one this table does not know.
 *
 * @upstream Packages/UEFIImage/Sources/UEFIImage/JedecIDs.swift#JedecIDs.chip
 */
export function jedecChip(id: number): JedecChip | undefined {
  return TABLE[id];
}

/**
 * The name alone, where the caller does not want the rest of the entry.
 *
 * @upstream Packages/UEFIImage/Sources/UEFIImage/JedecIDs.swift#JedecIDs.name
 */
export function jedecName(id: number): string | undefined {
  return TABLE[id]?.name;
}

/**
 * How many chips the table knows, for the test that the generated file is the
 * whole of its sources rather than a truncated read of it.
 *
 * @upstream Packages/UEFIImage/Sources/UEFIImage/JedecIDs.swift#JedecIDs.count
 */
export const JEDEC_COUNT = Object.keys(TABLE).length;

/**
 * How many of them each source named.
 *
 * @upstream Packages/UEFIImage/Sources/UEFIImage/JedecIDs.swift#JedecIDs.count
 */
export function jedecCount(source: JedecSource): number {
  return Object.values(TABLE).filter((chip) => chip.source === source).length;
}
"""


def locate_source(argv: list[str]) -> Path:
    if len(argv) > 1:
        return Path(argv[1])
    clone = os.environ.get("BYTERIPPER_REPO", "").strip() or str(ROOT.parent / "ByteRipper")
    return Path(clone) / "Packages" / "UEFIImage" / "Sources" / "UEFIImage" / "JedecIDs.swift"


def parse(path: Path) -> list[tuple[str, str, str | None, str]]:
    """The table's entries, in the file's order: id, name, size, source — with
    the group comments kept as entries whose id is None."""
    text = path.read_text(encoding="utf-8")
    if TABLE_OPEN not in text:
        sys.exit(f"{path}: no {TABLE_OPEN!r} line; the upstream layout changed")
    tail = text.split(TABLE_OPEN, 1)[1]
    end = tail.find("\n    ]")
    if end < 0:
        sys.exit(f"{path}: the table never closes")
    body = tail[:end].splitlines()

    entries: list[tuple[str, str, str | None, str]] = []
    for line in body:
        match = ENTRY.match(line)
        if match:
            raw_id, name, size, source = match.groups()
            entries.append((raw_id, name, int(size) if size != "nil" else None, source))
            continue
        group = GROUP.match(line)
        if group:
            entries.append((None, group.group(1).strip(), None, ""))
    return entries


def main(argv: list[str]) -> None:
    source = locate_source(argv)
    entries = parse(source)
    chips = [one for one in entries if one[0] is not None]
    if len(chips) < FLOOR:
        sys.exit(
            f"{source}: only {len(chips)} entries, under the floor of {FLOOR}; "
            "the read is truncated or the layout changed"
        )

    lines = [HEADER, TYPES, "const TABLE: Readonly<Record<number, JedecChip>> = {\n"]
    seen: set[str] = set()
    for raw_id, name, size, src in entries:
        if raw_id is None:
            lines.append(f"  // {name}\n")
            continue
        if raw_id in seen:
            sys.exit(f"{source}: the id {raw_id} is listed twice")
        seen.add(raw_id)
        # A decimal key: Biome's useSimpleNumberKeys refuses a hex number
        # literal in object position, and the table reads as ids, not values.
        kib = "undefined" if size is None else str(size)
        lines.append(f"  {int(raw_id, 16)}: {{ name: \"{name}\", sizeKB: {kib}, source: \"{src}\" }},\n")
    lines.append("};\n")
    lines.append(FOOTER)

    OUT.write_text("".join(lines), encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {len(chips)} chips from {source}")


if __name__ == "__main__":
    main(sys.argv)
